//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
2026 Copyright metal-stack Authors.
*/

// Code generated by conversion-gen. DO NOT EDIT.

package v1alpha1

import (
	unsafe "unsafe"

	config "github.com/fi-ts/gardener-extension-xdr/pkg/apis/config"
	configv1alpha1 "github.com/gardener/gardener/extensions/pkg/apis/config/v1alpha1"
	conversion "k8s.io/apimachinery/pkg/conversion"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

func init() {
	localSchemeBuilder.Register(RegisterConversions)
}

// RegisterConversions adds conversion functions to the given scheme.
// Public to allow building arbitrary schemes.
func RegisterConversions(s *runtime.Scheme) error {
	if err := s.AddGeneratedConversionFunc((*ControllerConfiguration)(nil), (*config.ControllerConfiguration)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_ControllerConfiguration_To_config_ControllerConfiguration(a.(*ControllerConfiguration), b.(*config.ControllerConfiguration), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*config.ControllerConfiguration)(nil), (*ControllerConfiguration)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_config_ControllerConfiguration_To_v1alpha1_ControllerConfiguration(a.(*config.ControllerConfiguration), b.(*ControllerConfiguration), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*TenantConfig)(nil), (*config.TenantConfig)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_TenantConfig_To_config_TenantConfig(a.(*TenantConfig), b.(*config.TenantConfig), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*config.TenantConfig)(nil), (*TenantConfig)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_config_TenantConfig_To_v1alpha1_TenantConfig(a.(*config.TenantConfig), b.(*TenantConfig), scope)
	}); err != nil {
		return err
	}
	return nil
}

func autoConvert_v1alpha1_ControllerConfiguration_To_config_ControllerConfiguration(in *ControllerConfiguration, out *config.ControllerConfiguration, s conversion.Scope) error {
	out.HealthCheckConfig = (*configv1alpha1.HealthCheckConfig)(unsafe.Pointer(in.HealthCheckConfig))
	out.TenantConfigs = *(*config.TenantConfigs)(unsafe.Pointer(&in.TenantConfigs))
	return nil
}

// Convert_v1alpha1_ControllerConfiguration_To_config_ControllerConfiguration is an autogenerated conversion function.
func Convert_v1alpha1_ControllerConfiguration_To_config_ControllerConfiguration(in *ControllerConfiguration, out *config.ControllerConfiguration, s conversion.Scope) error {
	return autoConvert_v1alpha1_ControllerConfiguration_To_config_ControllerConfiguration(in, out, s)
}

func autoConvert_config_ControllerConfiguration_To_v1alpha1_ControllerConfiguration(in *config.ControllerConfiguration, out *ControllerConfiguration, s conversion.Scope) error {
	out.HealthCheckConfig = (*configv1alpha1.HealthCheckConfig)(unsafe.Pointer(in.HealthCheckConfig))
	out.TenantConfigs = *(*TenantConfigs)(unsafe.Pointer(&in.TenantConfigs))
	return nil
}

// Convert_config_ControllerConfiguration_To_v1alpha1_ControllerConfiguration is an autogenerated conversion function.
func Convert_config_ControllerConfiguration_To_v1alpha1_ControllerConfiguration(in *config.ControllerConfiguration, out *ControllerConfiguration, s conversion.Scope) error {
	return autoConvert_config_ControllerConfiguration_To_v1alpha1_ControllerConfiguration(in, out, s)
}

func autoConvert_v1alpha1_TenantConfig_To_config_TenantConfig(in *TenantConfig, out *config.TenantConfig, s conversion.Scope) error {
	out.TenantId = in.TenantId
	out.ProxyList = *(*[]string)(unsafe.Pointer(&in.ProxyList))
	out.DistributionId = in.DistributionId
	out.CustomTag = in.CustomTag
	return nil
}

// Convert_v1alpha1_TenantConfig_To_config_TenantConfig is an autogenerated conversion function.
func Convert_v1alpha1_TenantConfig_To_config_TenantConfig(in *TenantConfig, out *config.TenantConfig, s conversion.Scope) error {
	return autoConvert_v1alpha1_TenantConfig_To_config_TenantConfig(in, out, s)
}

func autoConvert_config_TenantConfig_To_v1alpha1_TenantConfig(in *config.TenantConfig, out *TenantConfig, s conversion.Scope) error {
	out.TenantId = in.TenantId
	out.ProxyList = *(*[]string)(unsafe.Pointer(&in.ProxyList))
	out.DistributionId = in.DistributionId
	out.CustomTag = in.CustomTag
	return nil
}

// Convert_config_TenantConfig_To_v1alpha1_TenantConfig is an autogenerated conversion function.
func Convert_config_TenantConfig_To_v1alpha1_TenantConfig(in *config.TenantConfig, out *TenantConfig, s conversion.Scope) error {
	return autoConvert_config_TenantConfig_To_v1alpha1_TenantConfig(in, out, s)
}
