# After changing this file, please run `make patch-upstream-helm` and regenerate the CRD
{{- if .Capabilities.APIVersions.Has "metal-stack.io/v1" }}
# capabilities ok
{{- if .Values.proxyAddresses }}
apiVersion: metal-stack.io/v1
kind: ClusterwideNetworkPolicy
metadata:
  name: xdr-proxy-access
  namespace: {{ .Release.Namespace }}
  labels:
    labels: {{- include "cortex-xdr.labels" . | nindent 4 }}
spec:
  egress:
  {{- range .Values.proxyAddresses }}
  {{- $parts := split ":" . }}
  {{- if and $parts._0 $parts._1 }}
  - to:
    - cidr: {{ $parts._0 }}/32
    ports:
    - protocol: TCP
      port: {{ $parts._1 | int }}
  {{- end }}
  {{- end }}
{{- end }}
{{- end }}
