{{- $crd := lookup "apiextensions.k8s.io/v1" "CustomResourceDefinition" "" "clusterwidenetworkpolicies.metal-stack.io" }}
{{- if $crd }}
{{- if .Values.xdr.proxyAddresses }}
apiVersion: metal-stack.io/v1
kind: ClusterWideNetworkPolicy
metadata:
  name: xdr-proxy-access
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ include "gardener-extension-xdr.name" . }}
    chart: {{ include "gardener-extension-xdr.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  description: "Allow access to XDR proxy servers"
  egress:
  {{- range .Values.xdr.proxyAddresses }}
  {{- $parts := split ":" . }}
  {{- if and $parts._0 $parts._1 }}
  - to:
    - ipBlock:
        cidr: {{ $parts._0 }}/32
    ports:
    - protocol: TCP
      port: {{ $parts._1 | int }}
  {{- end }}
  {{- end }}
  podSelector: {}
  policyTypes:
  - Egress
{{- end }}
{{- end }}
