{{- if .Values.rbac.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "cortex-xdr.clusterRoleName" . }}
  labels: {{- include "cortex-xdr.labels" . | nindent 4 }}
rules:
- apiGroups: [""]
  resources: ["pods", "namespaces"]
  verbs: ["get", "list", "watch"]
{{- end -}}
