{{- if .Values.dockerPullSecret.create -}}
apiVersion: v1
kind: Secret
type: kubernetes.io/dockerconfigjson
metadata:
  name: {{ include "cortex-xdr.dockerPullSecretName" . }}
  labels: {{- include "cortex-xdr.labels" . | nindent 4 }}
  namespace: {{ .Values.namespace.name }}
data:
  .dockerconfigjson: {{ .Values.dockerPullSecret.value | quote }}
{{- end -}}
