{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "cortex-xdr.serviceAccountName" . }}
  labels: {{- include "cortex-xdr.labels" . | nindent 4 }}
  namespace: {{ .Values.namespace.name }}
{{- end -}}
