//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
2026 Copyright metal-stack Authors.
*/

// Code generated by conversion-gen. DO NOT EDIT.

package v1alpha1

import (
	xdr "github.com/fi-ts/gardener-extension-xdr/pkg/apis/xdr"
	conversion "k8s.io/apimachinery/pkg/conversion"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

func init() {
	localSchemeBuilder.Register(RegisterConversions)
}

// RegisterConversions adds conversion functions to the given scheme.
// Public to allow building arbitrary schemes.
func RegisterConversions(s *runtime.Scheme) error {
	if err := s.AddGeneratedConversionFunc((*XDRConfig)(nil), (*xdr.XDRConfig)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_XDRConfig_To_xdr_XDRConfig(a.(*XDRConfig), b.(*xdr.XDRConfig), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*xdr.XDRConfig)(nil), (*XDRConfig)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_xdr_XDRConfig_To_v1alpha1_XDRConfig(a.(*xdr.XDRConfig), b.(*XDRConfig), scope)
	}); err != nil {
		return err
	}
	return nil
}

func autoConvert_v1alpha1_XDRConfig_To_xdr_XDRConfig(in *XDRConfig, out *xdr.XDRConfig, s conversion.Scope) error {
	out.NoProxy = in.NoProxy
	out.CustomTag = in.CustomTag
	out.Tenant = in.Tenant
	return nil
}

// Convert_v1alpha1_XDRConfig_To_xdr_XDRConfig is an autogenerated conversion function.
func Convert_v1alpha1_XDRConfig_To_xdr_XDRConfig(in *XDRConfig, out *xdr.XDRConfig, s conversion.Scope) error {
	return autoConvert_v1alpha1_XDRConfig_To_xdr_XDRConfig(in, out, s)
}

func autoConvert_xdr_XDRConfig_To_v1alpha1_XDRConfig(in *xdr.XDRConfig, out *XDRConfig, s conversion.Scope) error {
	out.NoProxy = in.NoProxy
	out.CustomTag = in.CustomTag
	out.Tenant = in.Tenant
	return nil
}

// Convert_xdr_XDRConfig_To_v1alpha1_XDRConfig is an autogenerated conversion function.
func Convert_xdr_XDRConfig_To_v1alpha1_XDRConfig(in *xdr.XDRConfig, out *XDRConfig, s conversion.Scope) error {
	return autoConvert_xdr_XDRConfig_To_v1alpha1_XDRConfig(in, out, s)
}
